import {
  IsEnum,
  IsString,
  IsOptional,
  IsObject,
  IsUUID,
  IsBoolean,
  IsIP,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { ActivityType } from '../entities/activity-log.entity';

export class CreateActivityLogDto {
  @ApiProperty({
    enum: ActivityType,
    example: ActivityType.CREATE,
    description: 'Type of activity',
  })
  @IsEnum(ActivityType)
  type: ActivityType;

  @ApiProperty({
    example: 'Created new user',
    description: 'Description of the activity',
  })
  @IsString()
  action: string;

  @ApiPropertyOptional({
    example: { userId: '123', changes: { name: 'New Name' } },
    description: 'Additional details about the activity',
  })
  @IsObject()
  @IsOptional()
  details?: Record<string, any>;

  @ApiPropertyOptional({
    example: '192.168.1.1',
    description: 'IP address of the user',
  })
  @IsIP()
  @IsOptional()
  ipAddress?: string;

  @ApiPropertyOptional({
    example: 'Mozilla/5.0...',
    description: 'User agent string',
  })
  @IsString()
  @IsOptional()
  userAgent?: string;

  @ApiPropertyOptional({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'ID of the user who performed the action',
  })
  @IsUUID()
  @IsOptional()
  userId?: string;

  @ApiPropertyOptional({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'ID of the tenant where the action was performed',
  })
  @IsUUID()
  @IsOptional()
  tenantId?: string;

  @ApiPropertyOptional({
    example: 'User',
    description: 'Type of resource being acted upon',
  })
  @IsString()
  @IsOptional()
  resourceType?: string;

  @ApiPropertyOptional({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'ID of the resource being acted upon',
  })
  @IsString()
  @IsOptional()
  resourceId?: string;

  @ApiPropertyOptional({
    example: false,
    description: 'Whether this log was generated by the system',
  })
  @IsBoolean()
  @IsOptional()
  isSystemGenerated?: boolean;

  @ApiPropertyOptional({
    example: 'success',
    description: 'Status of the activity',
  })
  @IsString()
  @IsOptional()
  status?: string;
}
